### model
model_name_or_path: /home/ud202281368/model/llama3.1-8b-instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: bipartite, common_neighbor, connected_component, connectivity, degree, DFS, diameter, edge, hamiltonian_path, jaccard, maximum_flow, MST, neighbor, page_rank, predecessor, shortest_path, topological_sort
template: llama3
cutoff_len: 512
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama3.1-8b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: True
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
